CREATE TABLE USUARIO
(
    DOC_USER VARCHAR(15),
    NICK_USER VARCHAR(20),
    PASSWORD_USER VARCHAR(200),
    NOMBRE_USER VARCHAR(40),
    APELLIDOS_USER VARCHAR(40),
    CELULAR_USER VARCHAR(15),
    CORREO_USER VARCHAR(30),
    ID_PERFIL_USER INTEGER,
    ESTADO_USER INTEGER
)

CREATE TABLE TIPO_PERFIL
(
    ID_TIPO_PERFIL INTEGER,
    NOMBRE_TIPO_PERFIL VARCHAR(10)
)

