--Reglas para la Tabla Sexos
ALTER TABLE SEXOS ADD CONSTRAINT PK_SEXO PRIMARY KEY(id);

--Reglas para la Tabla Estados_Usuarios
ALTER TABLE ESTADOS_USUARIOS ADD CONSTRAINT PK_ESTADO_USUARIO PRIMARY KEY(id);

--Reglas para la Tabla Perfiles
ALTER TABLE PERFILES ADD CONSTRAINT PK_PERFIL PRIMARY KEY(id);

--Reglas para la Tabla Usuario
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIO PRIMARY KEY(identificacion);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_PERFIL_USUARIO FOREIGN KEY(perfil) REFERENCES PERFILES(id);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_ESTADO_USUARIO FOREIGN KEY(estado) REFERENCES ESTADOS_USUARIOS(id);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_SEXO_USUARIO FOREIGN KEY(sexo) REFERENCES SEXOS(id);

--Regla de la Tabla Recetas
ALTER TABLE RECETAS ADD CONSTRAINT PK_RECETA PRIMARY KEY(id);
ALTER TABLE RECETAS ADD CONSTRAINT FK_USUARIO_RECETA FOREIGN KEY(usuario) REFERENCES USUARIOS(identificacion) on delete cascade;

--Reglas de la Tabla Estados Citas
ALTER TABLE ESTADOS_CITAS ADD CONSTRAINT PK_ESTADO_CITA PRIMARY KEY(id);

--Regla de la Tabla Citas
ALTER TABLE CITAS ADD CONSTRAINT PK_CITAS PRIMARY KEY(id);
ALTER TABLE CITAS ADD CONSTRAINT FK_USUARIO_CITA FOREIGN KEY(usuario) REFERENCES USUARIOS(identificacion) on delete cascade;
ALTER TABLE CITAS ADD CONSTRAINT FK_ESTADO_CITA FOREIGN KEY(estado) REFERENCES ESTADOS_CITAS(id);